name: nifty-dev
channels:
  - conda-forge
dependencies:
  - python 3.12
  - numpy
  - xtensor >=0.26,<0.27
  - xtensor-python >=0.28,<0.29
  - libboost-devel
  - libvigra
  # Vigra Numpy is used at link time too
  - vigra
  - z5py >=2.0.20
  # build dependencies needed for z5
  - nlohmann_json
  - blosc
  - bzip2
  - zlib
