package:
  name: nifty
  version: v1.0.7


source:
  path: ..


build:
  number: 1000
  script: |
    # Install xtensor-python from GitHub source during build
    pip install git+https://github.com/maxstidbits/xtensor-python.git
    # Run the standard Python build
    python -m pip install . -vv


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python
    - boost-cpp >=1.63
    - hdf5 >=1.10
    - numpy >=1.15
    - blosc
    - z5py >=2.0.5
    - vigra
    - bzip2
    - zlib
    - xtensor
    # xtensor-python: Installed via pip during build process from custom GitHub source
    - pip
    - git  # Required for pip install from git repository
    - nlohmann_json

  run:
    - python
    - scikit-image
    - vigra
    - hdf5 >=1.10
    - numpy >=1.15
    - blosc
    - bzip2
    - zlib


test:
  imports:
    - nifty


about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  summary: Graph-based segmentation algorithms
