name: nifty-build-env
channels:
  - conda-forge
dependencies:
  - libboost-devel
  - cmake
  - compilers
  - h5py
  - nlohmann_json
  - numpy
  - scikit-image
  - xtensor
  - xtensor-python
  - vigra
  - z5py >=2.0.20
